##
# General config stuff
##

# Enables the use of CTRL+<arrow key> to jump to next whitespace in emacs
set-window-option -g xterm-keys on

# Stop renaming windows automatically
set-option -g allow-rename off

# Shortcut to reload tmux config file
bind r source-file ~/.tmux.conf ; display-message 'Config reloaded'

# Bind horizontal and vertical pane splitting into more sensible shortcuts (_ and | respectively)
bind | split-window -h
bind _ split-window -v
# Unbind the original splitting shortcuts
unbind '"'
unbind %

# Bind WASD (hold shift) to resize tmux panes
# '-r' makes these repeatable, so you only have to Ctrl+B once and then press the binds in succession
bind -r W resize-pane -U 10
bind -r S resize-pane -D 10
bind -r A resize-pane -L 10
bind -r D resize-pane -R 10

# Bind Left/Right to switch tmux panes
bind -r Left select-pane -L
bind -r Right select-pane -R

# Bind CTRL+Left/Right to switch tmux windows
bind -r C-Left previous-window
bind -r C-Right next-window

# Bind CTRL+SHIFT+Left/Right to reorder tmux windows
bind -r C-S-Left swap-window -t -1
bind -r C-S-Right swap-window -t +1

# Bind CTRL+m to decrement the current window number to the lowest unassigned number, filling gaps
bind C-m move-window

# Bind CTRL+k to kill a pane
bind k confirm-before -p "Kill this pane? (y/n)" kill-pane
# Bind CTRL+q to kill an entire window
bind q confirm-before -p "Kill Window '#I:#W'? (y/n)" kill-window
# Unbind the originaly kill keys
unbind &
unbind x


##
# Colors/theme starts here
##
STATUS_BAR_MESSAGE_TEXT_COLOR="#111111"
STATUS_BAR_MESSAGE_BACKGROUND_COLOR="#F5F5F5"

ACTIVE_WINDOW_TEXT_COLOR="#F5F5F5"
ACTIVE_WINDOW_BACKGROUND_COLOR="#141414"

INACTIVE_WINDOW_TEXT_COLOR="#A0A0A0"
INACTIVE_WINDOW_BACKGROUND_COLOR="#141414"

PANE_SEPARATOR_ACTIVE_COLOR="#E08505"
PANE_SEPARATOR_INACTIVE_COLOR="#333333"



#
##
###
# You shouldn't have to edit beyond here
###
##
#

##
# These apply the theme values defined above
##

# pane separators
set-option -g pane-border-fg $PANE_SEPARATOR_INACTIVE_COLOR
set-option -g pane-active-border-fg $PANE_SEPARATOR_ACTIVE_COLOR

# inactive window text (fg) and background (bg)
set-option -g status-fg $INACTIVE_WINDOW_TEXT_COLOR
set-option -g status-bg $INACTIVE_WINDOW_BACKGROUND_COLOR
set-option -g status-attr default

# active window text (fg) and background (bg)
set-window-option -g window-status-current-fg $ACTIVE_WINDOW_TEXT_COLOR
set-window-option -g window-status-current-bg $INACTIVE_WINDOW_BACKGROUND_COLOR

# tmux message text (fg) and background (bg)
set-option -g message-fg $STATUS_BAR_MESSAGE_TEXT_COLOR
set-option -g message-bg $STATUS_BAR_MESSAGE_BACKGROUND_COLOR
