# Bind r to reload this config
bind r "source-file ~/.tmux.conf ; display-message 'Config reloaded'"

# Stop renaming windows automatically
set-option -g allow-rename off

# Bind horizontal and vertical pane splitting to more sensible shortcuts (_ and | respectively)
bind | split-window -h
bind _ split-window -v
unbind '"'
unbind %

# Bind WASD (hold shift) to resize panes
# '-r' makes these repeatable, so you only have to Ctrl+B once and then press the binds in succession
bind -r W resize-pane -U 10
bind -r S resize-pane -D 10
bind -r A resize-pane -L 10
bind -r D resize-pane -R 10

# Bind Left/Right to switch panes
bind -r Left select-pane -L
bind -r Right select-pane -R

# Bind Ctrl+Left/Right to switch windows
bind -r C-Left previous-window
bind -r C-Right next-window

# Bind Ctrl+Shift+Left/Right to reorder windows
bind -r C-S-Left "swap-window -t -1 ; previous-window"
bind -r C-S-Right "swap-window -t +1 ; next-window"


##
# Colors/theme starts here
##

set-option -g pane-active-border-style "bg=#141414 fg=#8D5024"
set-option -g pane-border-style "bg=#141414 fg=#501E02"
set-option -g message-style "bg=#FFEEDD fg=#141414"
set-option -g status-style "bg=#141414 fg=#FFEEDD"
